# Solving Sudoku Puzzles
## Assignment Preamble
Please ensure you carefully read all of the details and instructions on the assignment page, this section, and the rest of the notebook. If anything is unclear at any time please post on the forum or ask a tutor well in advance of the assignment deadline.

In addition to all of the instructions in the body of the assignment below, you must also follow the following technical instructions for all assignments in this unit. *Failure to do so may result in a grade of zero.*
* [At the bottom of the page](#Submission-Test) is some code which checks you meet the submission requirements. You **must** ensure that this runs correctly before submission.
* Do not modify or delete any of the cells that are marked as test cells, even if they appear to be empty.
* Do not duplicate any cells in the notebook – this can break the marking script. Instead, insert a new cell (e.g. from the menu) and copy across any contents as necessary.

Remember to save and backup your work regularly, and double-check you are submitting the correct version.

This notebook is the primary reference for your submission. You may write code in separate `.py` files but it must be clearly imported into the notebook so that it runs without needing to reference those files, and you must explain clearly what functionality is contained in those files (through comments, markdown cells, etc).

As always, **the work you submit for this assignment must be entirely your own.** Do not copy or work with other students. Do not copy answers that you find online. These assignments are designed to help improve your understanding first and foremost – the process of doing the assignment is part of *learning*. They are also used to assess your ability, and so you must uphold academic integrity. Submitting plagiarised work risks your entire place on your degree.

**You must implement your own work.** You can and are encouraged to use helper libraries like `numpy`, but you must not use 3rd-party libraries or code that solves the assignment for you. *Even if it is properly referenced*, you only get marks for work you have done. If you are unsure, ask on the forum or ask a tutor directly.

**The pass mark for this assignment is 40%.** We expect that students, on average, will be able to produce a submission which gets a mark between 50-70% within the normal workload allocation for the unit, but this will vary depending on individual backgrounds. Please ask for help if you are struggling.

## Getting Started
For this assignment, you will be writing an agent that can solve sudoku puzzles. You should be familiar with sudoku puzzles from the unit material. You are given a 9x9 grid with some fixed values. To solve the puzzle, the objective is to fill the empty cells of the grid such that the numbers 1 to 9 appear exactly once in each row, column, and 3x3 block of the grid. 

Below is a sample puzzle along with its solution. 

<img src="images/sudoku.png" style="width: 50%;"/>

For this assignment you will need to submit:
1. The implementation for an agent which can solve sudoku puzzles – this notebook
 * You can use any algorithm you like, from the unit material or otherwise
 * Your code will be subject to automated testing, from which grades will be assigned based on whether it can solve sudokus of varying difficulty
 * To get a high grade on this assignment, the speed of your code will also be a factor – the quicker the better
 * There are some sample tests included below, make sure your code is compatible with the format of these tests
2. A text file that explains your approach and the decisions you made in your own words – a readme file
 * Submissions that do not include the written section will receive zero marks – **this part is mandatory**
 * You may write your file in plain text (.txt) or [Markdown](https://www.markdownguide.org/basic-syntax/) (.md)
 * To get top marks on this assignment, as well as getting a high grade from your implementation, you must also demonstrate excellent academic presentation in your written section

### Choice of Algorithm
The choice of algorithm to solve sudoku puzzles is up to you. We expect you will use search techniques from the unit, but you could make something up yourself, or do some independent research to find something else. You will need to evaluate and balance the trade-off between how well suited you think the algorithm is and how difficult it is to write, but there is some advice below.

You should also consider what *data structures* you use within your code. Certain algorithms will work much faster with certain data structures, and understanding this is considered part of understanding the algorithm itself. 

I suggest you implement *constraint satisfaction* as it is described in the unit material. A good implementation of a backtracking depth-first search with constraint propagation should be sufficient to get a good grade in the automated tests (roughly 60-70%). There is an example of constraint satisfaction on the eight-queens puzzle, and you could use this as a guide to help you get started.

You could also write a successful agent that uses the other search techniques you have seen in the unit so far: basic search, heuristic search, or local search. You may find these easier to implement, though they may perform less well. 

To get a high grade on this assignment will require a particularly efficient implementation of constraint satisfaction, or something which goes beyond the material we have presented. *This is left unguided and is not factored into the unit workload estimates.*

If you choose to implement more than one algorithm, please feel free to include your code and write about it in part two (readme file), but only the code in this notebook will be used in the automated testing.

## Sample Sudoku Puzzles
To get started, the cell below will load in some sample sudoku puzzles for you so you can see the format. There are sudokus provided of multiple difficulties (easier sudokus typically start with more digits provided). The cell below only loads the easiest, but there is another test cell lower in the notebook which will run your code against all of the provided puzzles.

Each sudoku is a 9x9 NumPy array of integers, where zero represents an empty square. Each difficulty comes with 15 sudokus, so when you load the file, it is stored in a 15x9x9 array.

In [1]:
import numpy as np

# Load sudokus
sudoku = np.load("data/very_easy_puzzle.npy")
print("very_easy_puzzle.npy has been loaded into the variable sudoku")
print(f"sudoku.shape: {sudoku.shape}, sudoku[0].shape: {sudoku[0].shape}, sudoku.dtype: {sudoku.dtype}")

# Load solutions for demonstration
solutions = np.load("data/very_easy_solution.npy")
print()

# Print the first 9x9 sudoku...
print("First sudoku:")
print(sudoku[0], "\n")

# ...and its solution
print("Solution of first sudoku:")
print(solutions[0])

very_easy_puzzle.npy has been loaded into the variable sudoku
sudoku.shape: (15, 9, 9), sudoku[0].shape: (9, 9), sudoku.dtype: int8

First sudoku:
[[1 0 4 3 8 2 9 5 6]
 [2 0 5 4 6 7 1 3 8]
 [3 8 6 9 5 1 4 0 2]
 [4 6 1 5 2 3 8 9 7]
 [7 3 8 1 4 9 6 2 5]
 [9 5 2 8 7 6 3 1 4]
 [5 2 9 6 3 4 7 8 1]
 [6 0 7 2 9 8 5 4 3]
 [8 4 3 0 1 5 2 6 9]] 

Solution of first sudoku:
[[1 7 4 3 8 2 9 5 6]
 [2 9 5 4 6 7 1 3 8]
 [3 8 6 9 5 1 4 7 2]
 [4 6 1 5 2 3 8 9 7]
 [7 3 8 1 4 9 6 2 5]
 [9 5 2 8 7 6 3 1 4]
 [5 2 9 6 3 4 7 8 1]
 [6 1 7 2 9 8 5 4 3]
 [8 4 3 7 1 5 2 6 9]]


## Part One
You should write all of your code for solving sudokus below this cell.

You must include a function called `sudoku_solver(sudoku)` which takes one sudoku puzzle (a 9x9 NumPy array) as input, and returns the solved sudoku as another 9x9 NumPy array. This is the function which will be tested. 

In [2]:
import numpy as np


# class for creating node objects that represent 1's in an exact cover matrix
class DancingNode:
    # constructor method
    # column_node is a ColumnObject which itself is an object that inherits from DancingNode
    # row is default 0 for column objects as these are not actually present in cover matrix
    # note that row values for regular nodes begin index at 1
    def __init__(self, column_node, row=0):
        # U,D,L,R,C attributes initialised to point to self
        # These will be updated to point between nodes during setup of AlgorithmX implementation
        self.up = self
        self.down = self
        self.right = self
        self.left = self

        # Column object allows us to keep track of position of node
        self.column_node = column_node
        # This also helps to find the node in the exact cover matrix to translate result back  into sudoku
        self.row = row

    # methods for creating links between nodes
    # note names are bi-directional as links are all bi-directional
    # this is done for shorter method names that are easier to read

    # method creates links for up and down pointers
    def link_up_down(self, node):
        self.down = node
        node.up = self

    # method creates links for right and left pointers
    def link_left_right(self, node):
        self.right = node
        node.left = self

    # methods for removing links
    # these implement the subtle trick behind the algorithm's efficiency as only the links are changed, the
    # actual node is still present

    # method removes link to this node, also connecting the nodes to the left and right of this node
    def remove_left_right(self):
        self.left.right = self.right
        self.right.left = self.left

    def remove_up_down(self):
        self.up.down = self.down
        self.down.up = self.up

    # methods put links back into data structure
    # note this more efficient than deleting and re-creating the current node
    # this node is never deleted so we can just re add the pointers left and right of it (hence name)

    # method to bring this node back by changing the pointers left and right of this node to point to this
    # node again.
    def re_add_left_right(self):
        self.left.right = self
        self.right.left = self

    #  method to bring this node back by changing the pointers above and below this node to point to this
    # node again.
    def re_add_up_down(self):
        self.up.down = self
        self.down.up = self


# This object inherits from DancingNode and is used to keep the order of the nodes in tact
class ColumnObject(DancingNode):
    # constructor method
    # name is to keep track of multiple column nodes
    def __init__(self, name):
        # run super constructor for object
        DancingNode.__init__(self, None)  # note this object has no column as it is itself a column so none is passed

        # name is an identifier to keep track of multiple column objects
        self.name = name
        # size keeps track of num of nodes in column which is useful for knowing which column to traverse during solve
        self.size = 0

    # cover method
    # this removes all objects in both horizontal and vertical positions linked to any nodes in the current column
    # note this is not the same as a deletion - this is to reduce the size of the matrix each time we add a column to
    # the final solution - we no longer need to search any of the nodes that are connected to this column
    def cover_column(self):
        self.remove_left_right()
        # i traces from top to bottom of column
        i = self.down
        while i != self:  # finished when wraps back round to i
            j = i.right  # same logic for j
            while j != i:
                j.remove_up_down()  # remove link to node j
                j.column_node.size -= 1

                j = j.right
            i = i.down

    # un-cover method
    # this undoes the actions of the above method.
    # this is used for backtracking when we no longer wish to have this column in the final solution
    def uncover_column(self):
        # i now traces from bottom up to undo operation
        i = self.up
        while i != self:
            j = i.left  # same logic for j
            while j != i:
                j.column_node.size += 1
                j.re_add_up_down()

                j = j.left
            i = i.up

        self.re_add_left_right()


# this class is an implementation of Donald Knuth's AlgorithmX
# it takes an exact cover matrix of 0's and 1's and selects rows that when put together give a row of only 1's
# this indicates all constraints have been met
class AlgorithmX:
    # constructor method
    # matrix is an exact cover matrix: a 2D array of 0's and 1's representing constraints
    def __init__(self, matrix):
        # this node will ne the entry point for the algorithm
        self.header = ColumnObject("Header")
        # array to store nodes in final solution for exact cover
        self.solution = []
        # flag used to signal a solution has been found
        self.solution_found = False
        # array to store the column nodes used in the algorithm - used to create the data structure
        self.column_nodes = []

        # the code below generates the data structure described in Knuth's paper used in the algorithm

        # create column node objects
        last = self.header
        # for loop also generates name for each column
        # starts from 1 as header is first column object, so first column is column 1 NOT 0
        for column in range(1, len(matrix[0]) + 1):
            new_column_node = ColumnObject(column)  # create column object
            last.link_left_right(new_column_node)  # link to last column object
            self.column_nodes.append(new_column_node)
            last = new_column_node  # update last column object for next cycle
        # link last column node
        last.link_left_right(self.header)

        # create dancing nodes and link horizontally as they are created
        dancing_nodes = []
        # create link by row
        for row in range(0, len(matrix)):
            row_nodes = []
            prev = None
            for col in range(0, len(matrix[0])):
                # where there is a 1 in the matrix, we need a dancing node
                if matrix[row][col] == 1:
                    column_node = self.column_nodes[col]
                    new_dancing_node = DancingNode(column_node, row + 1)
                    column_node.size += 1

                    row_nodes.append(new_dancing_node)

                    # if statement handles error when trying to link first element in row to previous
                    # as previous hasn't been created yet
                    if prev is None:
                        first = new_dancing_node
                        prev = new_dancing_node
                    else:
                        prev.link_left_right(new_dancing_node)
                        prev = new_dancing_node

                else:
                    row_nodes.append(None)

            if not(prev is None):  # when all zeros we can't link
                prev.link_left_right(first)
            dancing_nodes.append(row_nodes)

        # link nodes down
        last_in_column = self.header.right
        column_node = self.header.right
        for col in range(0, len(matrix[0])):

            for node_row in dancing_nodes:

                if not (node_row[col] is None):  # if none then it is a c column object
                    last_in_column.link_up_down(node_row[col])
                    last_in_column = node_row[col]

            last_in_column.link_up_down(column_node)
            last_in_column = column_node.right
            column_node = column_node.right

    # methods for choosing next column object during solve method
    # first method is less efficient

    # this chooses the next column right of header
    def choose_column_object(self):
        return self.header.right

    # this returns the column with the smallest number of 1's as this should reduce the branching factor
    # during the search this is much more efficient, particularly for larger problems
    def choose_column_object_efficient(self):
        smallest_b = self.header.right
        compare = smallest_b.right
        while compare != self.header:  # iterate through each column node
            if compare.size < smallest_b.size:  # is this column the new smallest?
                smallest_b = compare  # if yes, update smallest
            compare = compare.right  # next column

        return smallest_b

    # solve method for finding a solution to exact cover problem
    # k is an int which keeps track of recursive depth
    def solve(self, k):
        # implement algorithm x
        # returns solution as choices of node objects in solution
        if self.header.right == self.header:
            # then all columns covered so all constraints met so solution can be returned
            self.solution_found = True

        else:  # recursive depth first search with smart guessing for which column to traverse
            # print("Branches:", self.branches)
            # choose column object to try adding to solution
            column_object = self.choose_column_object_efficient()
            # cover column to remove conflicting nodes as they don't need to be checked
            column_object.cover_column()

            r = column_object.down
            while r != column_object:
                # add all the nodes below this one as they are all in the solution too if this column is
                self.solution.append(r)
                # cover columns that conflict with the nodes that have just been added
                j = r.right
                while j != r:
                    j.column_node.cover_column()
                    j = j.right
                # recursive call - try adding another column to the solution
                # this will keep being reached until the matrix is empty
                self.solve(k + 1)

                # if a solution was found un-wind
                if self.solution_found:
                    return True
                # else the column we just added isn't part of the solution so remove it
                r = self.solution.pop()

                # similarly, add back all the nodes that were removed
                column_object = r.column_node

                j = r.left
                while j != r:
                    j.column_node.uncover_column()
                    j = j.left

                r = r.down
            # un cover column as it is not in the solution
            column_object.uncover_column()


def sudoku_to_constraints(sudoku_grid):
    # There are 9 (rows) x 9 (columns) x 9 (values) rows = 729 rows
    # There are 9 x 9(row/value combinations) + 9 x 9 (column/value combinations) + 9x9 (box/value combinations) = 324 columns

    binary_matrix = [[0 for col in range(0, 81 * 4)] for row in range(0, 729)]  # define shape

    # The below add in all the constraints for a blank sudoku and the effect on each
    # constraint of any given value being in any given position

    # cell constraints
    # every cell is 1-9
    # for every cell
    offset = 0

    for column in range(0, 81):
        for row in range(0, 9):
            binary_matrix[row + column * 9][column + offset] = 1

    offset += 81

    # row constraints
    # only 1-9 in each row
    # for every value
    # for every row

    for repeat in range(0, 729, 9):
        col = 9 * (repeat // 81)
        for row in range(0, 9):
            binary_matrix[row + repeat][col + offset] = 1
            col += 1

    offset += 81

    # column constraints
    # only 1-9 in each column
    # for every value
    # for every column

    for repeat in range(0, 729, 81):
        for row in range(0, 81):
            binary_matrix[row + repeat][row + offset] = 1

    offset += 81

    # block constraints
    # cascade 3 times
    # then shift along 9 and cascade again <- do 3 times
    # then shift by 9 <- do this 4 times
    row_shift = 0
    # do 4 times, and shift by 9 each time
    for big_shift in range(0, 3):
        for outer_repeat in range(0, 3):
            # shift cascade over by 9
            for small_shift in range(0, 3):
                # cascade 3 times
                for repeat in range(0, 3):
                    for row in range(0, 9):
                        binary_matrix[row + row_shift][row + offset + 27 * big_shift + 9 * small_shift] = 1
                    row_shift += 9

    # The below now adjusts the blank matrix according to the clues
    # Note the above is always the same so could be stored locally rather than re-creating it for every puzzle

    # remove rows conflicting with clues
    for row in range(0, len(sudoku_grid)):
        for col in range(0, len(sudoku_grid[0])):
            if sudoku_grid[row][col] != 0:

                num = sudoku_grid[row][col]
                c = 9 * col + 81 * row

                for remove in range(0, 9):
                    if remove + 1 == num:
                        pass
                    else:
                        binary_matrix[c + remove] = [0] * 324

    return binary_matrix


# method to translate solution
def get_sudoku_solution(solution):
    # solution is currently in reverse order due to depth first search so reverse
    solution.reverse()
    result = np.zeros((9, 9))  # pre-defined shape for sudoku grid
    # iterate through each node object in the solution
    for node in solution:
        # The below code translates positions in the constraints matrix into sudoku row and column meaning
        row_column_node = node

        # Let the smallest value be the current number of times there have been 9 rows
        iterations = row_column_node.column_node.name
        # compare to next column node
        next_column_node = node.right
        while next_column_node != node:
            # if this is the new smallest
            if next_column_node.column_node.name < iterations:
                # update smallest
                iterations = next_column_node.column_node.name
                row_column_node = next_column_node
            next_column_node = next_column_node.right

        # Do calcuations to find actual position in matrix
        row_col = row_column_node.column_node.name - 1
        
        num_col = row_column_node.right.column_node.name - 1 # - 1 to deal with 9m % 9 = 0 

        row = row_col // 9  # row is just int div of 9
        column = row_col % 9  # col counts 1-9 so is just modulo 9
        num = (num_col % 9) + 1  # this also counts hence modulo, but

        # update value in result matrix
        result[row][column] = num
    # if there have been no updates, the solution is just zeros so should be updated to -1's
    if result[0][0] == 0:
        # then no solution so return -1's
        no_solution = np.empty((9, 9))
        no_solution.fill(-1)
        return no_solution
    else:
        return result


def sudoku_solver(sudoku):
    """
        Solves a Sudoku puzzle and returns its unique solution.

        Input
            sudoku : 9x9 numpy array
                Empty cells are designated by 0.

        Output
            9x9 numpy array of integers
                It contains the solution, if there is one. If there is no solution, all array entries should be -1.
        """
    solver = AlgorithmX(sudoku_to_constraints(sudoku))
    solver.solve(0)
    return get_sudoku_solution(solver.solution)


All of your code must go above this cell. You may add additional cells into the notebook if you wish, but do not duplicate or copy/paste cells as this can interfere with the grading script.

### Testing Details
There are four difficulties of sudoku provided: very easy, easy, medium, and hard. There are 15 sample sudokus in each category, with solutions as well. Difficulty was determined using reference solvers, but your code may vary; it is conceivable that your code will find some sudokus much easier or harder within a given category, or even between categories.

*All categories that are easy and above will contain* ***invalid initial states***, that is, sudoku puzzles with no solution. In this case, your function should return a 9x9 NumPy array whose values are all equal to -1.

When we test your code, we will firstly test it on the *same* very easy puzzles that you have been given. Then we will test it on additional *hidden* sudokus from each difficulty in turn, easy and up – many more than 15 of each. Grades are awarded based on whether your code can solve the puzzles. For high grades on the hard puzzles, execution time will also be a factor. 

All puzzles must take under 20 seconds each on the test machine to count as successful – if it takes longer, it will timeout. Note that this is a maximum, not a goal. Higher grades require better performance on harder puzzles. As a very rough benchmark, you should be aiming for an average of under a second per puzzle. Hardware varies, but all tests will take place on the same modern desktop machine. Our ‘standard constraint satisfaction’ implementation takes about 0.001 seconds per puzzle for the very easy category, but struggles to solve some of the hard puzzles within the time limit.

***The hard sudokus are labelled as hard for a reason.*** We expect most submissions will not be able to solve them in a reasonable length of time. Use the stop button (■) on the toolbar if you need to terminate your code because it is taking too long.

The best way to improve the performance of your code is through a detailed understanding and smart choice of AI algorithms and data structures. This assignment is ***not*** meant to test your ability to write multi-threaded code or any other kind of high-performance code optimisations. 

#### Test Cell
The following code will run your solution over the provided sudoku puzzles. To enable it, set the constant `SKIP_TESTS` to `False`. If you fail any tests of one difficulty, the code will stop, but you can modify this behaviour if you like.

**IMPORTANT**: you must set `SKIP_TESTS` back to `True` before submitting this file!

In [3]:
SKIP_TESTS = True

def tests():
    import time
    difficulties = ['very_easy', 'easy', 'medium', 'hard']

    for difficulty in difficulties:
        print(f"Testing {difficulty} sudokus")
        
        sudokus = np.load(f"data/{difficulty}_puzzle.npy")
        solutions = np.load(f"data/{difficulty}_solution.npy")
        
        count = 0
        for i in range(len(sudokus)):
            sudoku = sudokus[i].copy()
            print(f"This is {difficulty} sudoku number", i)
            print(sudoku)
            
            start_time = time.process_time()
            your_solution = sudoku_solver(sudoku)
            end_time = time.process_time()
            
            print(f"This is your solution for {difficulty} sudoku number", i)
            print(your_solution)
            
            print("Is your solution correct?")
            if np.array_equal(your_solution, solutions[i]):
                print("Yes! Correct solution.")
                count += 1
            else:
                print("No, the correct solution is:")
                print(solutions[i])
            
            print("This sudoku took", end_time-start_time, "seconds to solve.\n")

        print(f"{count}/{len(sudokus)} {difficulty} sudokus correct")
        if count < len(sudokus):
            break
            
if not SKIP_TESTS:
    tests()

## Submission Test
The following cell tests if your notebook is ready for submission. **You must not skip this step!**

Restart the kernel and run the entire notebook (Kernel → Restart & Run All). Now look at the output of the cell below. 

*If there is no output, then your submission is not ready.* Either your code is still running (did you forget to skip tests?) or it caused an error.

As previously mentioned, failing to follow these instructions can result in a grade of zero.

In [4]:
def submission_tests():
    import sys
    import pathlib

    fail = False;

    if not SKIP_TESTS:
        fail = True;
        print("You must set the SKIP_TESTS constant to True in the cell above.")

    p1 = pathlib.Path('./readme.txt')
    p2 = pathlib.Path('./readme.md')
    if not (p1.is_file() or p2.is_file()):
        fail = True;
        print("You must include a separate file called readme.txt or readme.md in your submission.")

    p3 = pathlib.Path('./sudoku.ipynb')
    if not p3.is_file():
        fail = True
        print("This notebook file must be named sudoku.ipynb")

    if "sudoku_solver" not in globals():
        fail = True;
        print("You must include a function called sudoku_solver which accepts a numpy array.")
    else: 
        sudoku = np.load("data/very_easy_puzzle.npy")[0]
        solution = np.load("data/very_easy_solution.npy")[0]

        if not np.array_equal(sudoku_solver(sudoku), solution):
            print("Warning:")
            print("Your sudoku_solver function does not correctly solve the first sudoku.")
            print()
            print("Your assignment is unlikely to get any marks from the autograder. While we will")
            print("try to check it manually to assign some partial credit, we encourage you to ask")
            print("for help on the forum or directly to a tutor.")
            print()
            print("Please use the readme file to explain your code anyway.")

    if fail:
        print()
        sys.stderr.write("Your submission is not ready! Please read and follow the instructions above.")
    else:
        print("All checks passed. When you are ready to submit, upload the notebook and readme file to the")
        print("assignment page, without changing any filenames.")
        print()
        print("If you need to submit multiple files, you can archive them in a .zip file. (No other format.)")
        
submission_tests()

All checks passed. When you are ready to submit, upload the notebook and readme file to the
assignment page, without changing any filenames.

If you need to submit multiple files, you can archive them in a .zip file. (No other format.)


In [5]:
# This is a TEST CELL. Do not delete or change.